<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>TripService</AssemblyName>
    <RootNamespace>TripService</RootNamespace>
    <IsServiceFabricServiceProject>true</IsServiceFabricServiceProject>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ServiceFabric.Services" Version="8.7.157" />
    <PackageReference Include="Microsoft.ServiceFabric.AspNetCore.Kestrel" Version="8.7.157" />
    <PackageReference Include="Microsoft.ServiceFabric.Diagnostics.Internal" Version="8.7.157" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PackageRoot\**" Exclude="PackageRoot\**\*.user">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
